### ISSUE TITLE
Option to remove image masks

### ISSUE THREAD

**Issue by OshitaYoichi** [Spaceman-Labs/SMPageControl#3]
I don't seem to find a public way to remove the image masks.

The app which I'm working on has rectangle images for indicators.

So changing the following line:

CGContextFillEllipseInRect(context, CGRectMake(centeredXOffset, yOffset, _indicatorDiameter, _indicatorDiameter));

to:

CGContextFillEllipseInRect(context, CGRectMake(centeredXOffset, yOffset, _indicatorDiameter, _indicatorDiameter));

did it for me.

Could you provide a public way of disabling image masks for ease of use?

**Comment by jerryhjones** [comment]
Sorry, I'm not sure I follow. I think it might have been a mistake, but your two lines of code are the same.

Are you trying to change the mask for all the indicators, or trying to just make square indicators instead of circles?

**Comment by OshitaYoichi** [comment]
I wanted to remove the mask, so it would not cut off my custom image.

In this case it was a rectangle, but I could use a more complex image that I wouldn't want masked.

**Comment by jerryhjones** [comment]
So, your using a mask _and_ custom images? Or there is some unnecessary
clipping going on?

Any chance you could provide a sample in a gist, or with some screenshots?

**Comment by OshitaYoichi** [comment]
I use a rectangular image and the mask which you use by default clips a circle out of it, so I changed the above function to CGContextFillRect. I accidentally copy pasted the same line of code in my initial issue description.

The idea here is to have a public option of disabling all masks on the indicator images without changing the internals of your code.

A round rect image like the one attached would be a problem to display without such an option.
![blueButton](https://f.cloud.github.com/assets/938971/88207/447fa566-64e2-11e2-91b3-432ade1c2f54.gif)

**Comment by jerryhjones** [comment]
I have had trouble reproducing this. If you've fixed the problem, do you mind submitting a pull request with your changes?
